### ISSUE TITLE
Additional files to have copier create

### ISSUE THREAD

**Issue by dmurphy18** [salt-extensions/salt-extension-copier#14]
First used copier to create salt extension for Cassandra and noticed some generic files which copier could make as part of the process.
The files are as follows:

- CONTRIBUTING.md
- CODE-OF-CONDUCT.md
- NOTICE.txt

Looked at https://github.com/salt-extensions/saltext-azurerm/tree/main for examples:

Also once the salt extension is created with copier, these should be instruction in how to get the new extension submitted to the salt-extensions repository

**Comment by lkubb** [comment]
Thanks for trying out this template! Already prepared a PR for the new files.

I'm going to split the documentation part into a separate issue since I think it would be best if the working group would provide official instructions (https://github.com/salt-extensions/salt-extension-copier/issues/15).
